#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""benefits.json から銘柄ごとの静的ページ(benefits/<ticker>.html)を生成し、
benefits.html の静的一覧と sitemap.xml を更新する。

push 前に必ず実行すること:
    python scripts/build_benefits_pages.py

標準ライブラリのみ使用。何度流しても同じ入力からは同じ出力になる(冪等)。
"""
import glob
import html
import json
import os
import re
import subprocess

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_PATH = os.path.join(ROOT, "data", "benefittracker", "benefits.json")
BENEFITS_DIR = os.path.join(ROOT, "benefits")
BENEFITS_HTML = os.path.join(ROOT, "benefits.html")
SITEMAP_PATH = os.path.join(ROOT, "sitemap.xml")
BASE_URL = "https://hirottarow.github.io/hiroai-portal/"

STATIC_LIST_BEGIN = "<!-- BEGIN STATIC BENEFIT LIST (auto-generated by scripts/build_benefits_pages.py) -->"
STATIC_LIST_END = "<!-- END STATIC BENEFIT LIST -->"

# トップレベルの sitemap から除外するページ
# - tool-japan-map-display.html: OBS表示専用ビュー、単独ページとして無意味
# - google*.html: Search Console 所有権確認用トークンファイル、検索対象コンテンツではない
EXCLUDE_FROM_TOP_SITEMAP = {"tool-japan-map-display.html"}
EXCLUDE_PATTERNS = (re.compile(r"^google[0-9a-f]+\.html$"),)


def is_excluded(fname):
    if fname in EXCLUDE_FROM_TOP_SITEMAP:
        return True
    return any(p.match(fname) for p in EXCLUDE_PATTERNS)


def esc(value):
    return html.escape(str(value), quote=True)


def load_data():
    with open(DATA_PATH, encoding="utf-8") as f:
        return json.load(f)


def git_lastmod(relpath):
    out = subprocess.run(
        ["git", "log", "-1", "--format=%ad", "--date=short", "--", relpath],
        capture_output=True, text=True, cwd=ROOT,
    ).stdout.strip()
    return out or None


PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description}">
    <link rel="canonical" href="{canonical}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description}">
    <meta property="og:type" content="website">
    <meta property="og:url" content="{canonical}">
    <meta property="og:image" content="{base}logo.png">
    <meta name="twitter:card" content="summary">
    <script type="application/ld+json">
{jsonld}
    </script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;800&family=Noto+Sans+JP:wght@300;400;700&display=swap" rel="stylesheet">
    <style>
        :root {{
            --bg-color: #FAF6F0;
            --primary-color: #8B5A2B;
            --secondary-color: #5A4A42;
            --text-color: #2C2520;
            --card-bg: #FFFFFF;
            --accent-color: #EAD8C3;
            --font-outfit: 'Outfit', 'Noto Sans JP', sans-serif;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ font-family: var(--font-outfit); background-color: var(--bg-color); color: var(--text-color); line-height: 1.6; padding-bottom: 60px; }}
        header {{ background-color: rgba(90, 74, 66, 0.95); position: sticky; top: 0; z-index: 100; padding: 15px 5%; display: flex; justify-content: space-between; align-items: center; box-shadow: 0 4px 20px rgba(0,0,0,0.05); }}
        .logo {{ color: #FFFFFF; font-weight: 800; font-size: 18px; text-decoration: none; }}
        nav a {{ color: #FFFFFF; text-decoration: none; font-weight: 600; font-size: 13px; margin-left: 16px; }}
        nav a:hover {{ color: var(--accent-color); }}
        .breadcrumb {{ max-width: 760px; margin: 20px auto 0; padding: 0 5%; font-size: 13px; color: var(--secondary-color); }}
        .breadcrumb a {{ color: var(--primary-color); text-decoration: none; }}
        .container {{ max-width: 760px; margin: 0 auto; padding: 16px 5% 30px; }}
        h1 {{ font-size: 24px; margin-bottom: 4px; }}
        .subtitle {{ font-size: 15px; color: var(--primary-color); font-weight: 600; margin-bottom: 18px; }}
        .info-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 10px; margin-bottom: 20px; }}
        .info-item {{ background: var(--card-bg); border-radius: 10px; padding: 12px 14px; box-shadow: 0 3px 10px rgba(0,0,0,0.04); }}
        .info-item .label {{ font-size: 11px; color: var(--secondary-color); }}
        .info-item .value {{ font-size: 15px; font-weight: 700; margin-top: 2px; }}
        .section {{ margin-top: 20px; }}
        .section h2 {{ font-size: 15px; color: var(--secondary-color); margin-bottom: 6px; }}
        .section p {{ font-size: 14px; white-space: pre-line; }}
        .updated {{ font-size: 12px; color: var(--secondary-color); margin-top: 24px; }}
        .app-banner {{ margin-top: 26px; background: linear-gradient(135deg, #8B5A2B 0%, #6B4520 100%); color: #FFF; border-radius: 14px; padding: 18px; font-size: 13.5px; }}
        .app-banner strong {{ display: block; font-size: 15px; margin-bottom: 6px; }}
        .footer-links {{ margin-top: 40px; text-align: center; font-size: 13px; }}
        .footer-links a {{ color: var(--secondary-color); margin: 0 10px; }}
        .copyright {{ text-align: center; font-size: 12px; color: var(--secondary-color); margin-top: 16px; }}
    </style>
</head>
<body>
    <header>
        <a class="logo" href="../index.html">ひろ@AI遊び場</a>
        <nav>
            <a href="../benefits.html">株主優待</a>
            <a href="../tools.html">ツール</a>
            <a href="../privacy.html">プライバシーポリシー</a>
        </nav>
    </header>

    <div class="breadcrumb"><a href="../index.html">トップ</a> &rsaquo; <a href="../benefits.html">株主優待</a> &rsaquo; {company_esc}</div>

    <div class="container">
        <h1>{company_esc}（{ticker_esc}）の株主優待</h1>
        <div class="subtitle">{title_esc}</div>

        <div class="info-grid">
{info_items}
        </div>
{sections}
        <div class="updated">データ更新日: {updated_at_esc}{audited_line}</div>

        <div class="app-banner">
            <strong>&#128241; 手持ちの優待をアプリで管理</strong>
            この情報は、株主優待の残高・期限管理アプリ「BenefitTracker」の優待辞書と同じデータです。現在 Google Play でクローズドテストを実施中です。
        </div>

        <div class="footer-links">
            <a href="../index.html">ホーム</a>
            <a href="../benefits.html">株主優待 一覧に戻る</a>
            <a href="../terms.html">利用規約</a>
            <a href="../privacy.html">プライバシーポリシー</a>
        </div>
        <div class="copyright">&copy; 2026 Hiro @ AI Playground. All Rights Reserved.</div>
    </div>
</body>
</html>
"""


def star_text(rating):
    try:
        n = max(0, min(5, int(rating)))
    except (TypeError, ValueError):
        return None
    return "★" * n + "☆" * (5 - n)


def build_info_items(t):
    items = []
    if t.get("category"):
        items.append(("カテゴリ", t["category"]))
    if t.get("exchange"):
        items.append(("上場市場", t["exchange"]))
    if t.get("balance"):
        unit = t.get("balanceUnit") or "円"
        items.append(("優待の目安", f"{t['balance']:,}{unit}"))
    stars = star_text(t.get("rating"))
    if stars:
        items.append(("おすすめ度", stars))
    html_lines = []
    for label, value in items:
        html_lines.append(
            f'            <div class="info-item"><div class="label">{esc(label)}</div>'
            f'<div class="value">{esc(value)}</div></div>'
        )
    return "\n".join(html_lines)


def build_sections(t):
    sections = []
    if t.get("usableStores"):
        sections.append(("使えるお店", t["usableStores"]))
    if t.get("usageNotes"):
        sections.append(("使い方の注意", t["usageNotes"]))
    if t.get("description"):
        sections.append(("詳しい情報", t["description"]))
    if t.get("shipMonths"):
        months = ",".join(m.strip() + "月" for m in str(t["shipMonths"]).split(",") if m.strip())
        if months:
            sections.append(("発送目安", months + "ごろ"))
    html_blocks = []
    for label, value in sections:
        html_blocks.append(
            f'        <div class="section"><h2>{esc(label)}</h2><p>{esc(value)}</p></div>'
        )
    return "\n".join(html_blocks)


def build_description(t):
    parts = [f"{t['company']}（{t['ticker']}）の株主優待「{t.get('title') or t['company']}」の詳細ページです。"]
    if t.get("category"):
        parts.append(f"カテゴリ: {t['category']}。")
    if t.get("balance"):
        unit = t.get("balanceUnit") or "円"
        parts.append(f"優待の目安は{t['balance']:,}{unit}です。")
    return "".join(parts)


def build_page(t, updated_at):
    ticker = t["ticker"]
    company = t["company"]
    title = f"{company}（{ticker}）の株主優待 | ひろ@AI遊び場"
    description = build_description(t)
    canonical = f"{BASE_URL}benefits/{ticker}.html"

    jsonld = {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": 1, "name": "ホーム", "item": f"{BASE_URL}index.html"},
            {"@type": "ListItem", "position": 2, "name": "株主優待", "item": f"{BASE_URL}benefits.html"},
            {"@type": "ListItem", "position": 3, "name": company, "item": canonical},
        ],
    }

    audited_line = ""
    if t.get("auditedAt"):
        audited_line = f" ／ 銘柄情報の最終確認日: {esc(t['auditedAt'])}"

    return PAGE_TEMPLATE.format(
        title=esc(title),
        description=esc(description),
        canonical=canonical,
        base=BASE_URL,
        jsonld=json.dumps(jsonld, ensure_ascii=False, indent=2),
        company_esc=esc(company),
        ticker_esc=esc(ticker),
        title_esc=esc(t.get("title") or ""),
        info_items=build_info_items(t),
        sections=build_sections(t),
        updated_at_esc=esc(updated_at),
        audited_line=audited_line,
    )


def write_pages(templates, updated_at):
    os.makedirs(BENEFITS_DIR, exist_ok=True)
    existing = set(os.path.basename(p) for p in glob.glob(os.path.join(BENEFITS_DIR, "*.html")))
    written = set()
    for t in templates:
        ticker = t.get("ticker")
        if not ticker:
            raise ValueError(f"ticker が空です: {t.get('company')}")
        fname = f"{ticker}.html"
        path = os.path.join(BENEFITS_DIR, fname)
        content = build_page(t, updated_at)
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(content)
        written.add(fname)
    stale = existing - written
    for fname in stale:
        os.remove(os.path.join(BENEFITS_DIR, fname))
    return written, stale


def update_benefits_html(templates):
    with open(BENEFITS_HTML, encoding="utf-8") as f:
        content = f.read()

    items = sorted(templates, key=lambda t: t.get("ticker", ""))
    lines = [STATIC_LIST_BEGIN, '<ul class="static-benefit-list">']
    for t in items:
        ticker = t["ticker"]
        company = t["company"]
        lines.append(f'<li><a href="benefits/{esc(ticker)}.html">{esc(company)}</a></li>')
    lines.append("</ul>")
    lines.append(STATIC_LIST_END)
    block = "\n".join(lines)

    old_list_div = '<div id="list"><div class="status">読み込み中…</div></div>'
    new_list_div = f'<div id="list">\n{block}\n</div>'

    if STATIC_LIST_BEGIN in content:
        pattern = re.compile(
            re.escape(STATIC_LIST_BEGIN) + r".*?" + re.escape(STATIC_LIST_END), re.S
        )
        content, n = pattern.subn(block, content, count=1)
        if n != 1:
            raise ValueError("既存の静的一覧ブロックの置換に失敗しました")
    elif old_list_div in content:
        content = content.replace(old_list_div, new_list_div, 1)
    else:
        raise ValueError("benefits.html に挿入先(#list)が見つかりません")

    with open(BENEFITS_HTML, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)


def build_sitemap(templates, updated_at):
    top_files = sorted(
        f for f in glob.glob(os.path.join(ROOT, "*.html"))
        if not is_excluded(os.path.basename(f))
    )

    lines = ['<?xml version="1.0" encoding="UTF-8"?>',
             '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']

    for path in top_files:
        fname = os.path.basename(path)
        lm = git_lastmod(fname)
        lines.append("  <url>")
        lines.append(f"    <loc>{BASE_URL}{fname}</loc>")
        if lm:
            lines.append(f"    <lastmod>{lm}</lastmod>")
        lines.append("  </url>")

    for t in sorted(templates, key=lambda x: x.get("ticker", "")):
        ticker = t["ticker"]
        lines.append("  <url>")
        lines.append(f"    <loc>{BASE_URL}benefits/{ticker}.html</loc>")
        lines.append(f"    <lastmod>{updated_at}</lastmod>")
        lines.append("  </url>")

    lines.append("</urlset>")
    lines.append("")

    with open(SITEMAP_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))

    return len(top_files) + len(templates)


def main():
    data = load_data()
    templates = data.get("templates", [])
    updated_at = data.get("updatedAt", "")

    written, stale = write_pages(templates, updated_at)
    update_benefits_html(templates)
    url_count = build_sitemap(templates, updated_at)

    print(f"templates: {len(templates)}")
    print(f"pages written: {len(written)}")
    print(f"stale pages removed: {len(stale)}")
    print(f"sitemap urls: {url_count}")


if __name__ == "__main__":
    main()
